name: chicago-crash-workflow

on:
  push:
    branches: ["*"]

jobs:
  build:
    name:  Build Repo
    runs-on: ubuntu-latest

    steps:
      # you will add steps here
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Go Extractor
        run: |
          cd extractor
          go mod tidy
          go build ./...

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Test Python imports
        run: |
          python -c "import sys; sys.path.insert(0, 'transformer'); import transformer"
          python -c "import sys; sys.path.insert(0, 'cleaner'); import cleaner"
          python -c "import sys; sys.path.insert(0, 'cleaner'); import cleaning_rules"
          python -c "import sys; sys.path.insert(0, 'cleaner'); import duckdb_writer"
  
  docker-validation:
    name: Validate docker services
    runs-on: ubuntu-latest
    needs: build

    steps:
      # steps come here
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build key services with docker compose
        run: |
          docker compose -f docker-compose.yml build extractor
          docker compose -f docker-compose.yml build transformer
          docker compose -f docker-compose.yml build cleaner
          docker compose -f docker-compose.yml build streamlit

      - name: Validate docker-compose.yml
        run: |
          docker compose -f docker-compose.yml config

  sanity-check:
    name: Check everything is running correctly
    runs-on: ubuntu-latest
    needs: docker-validation

    steps:
      # steps here
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Extractor help test
        run: |
          cd extractor
          go run main.go --help

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Transformer import test
        run: |
          python - <<EOF
          import sys
          sys.path.insert(0, 'transformer')
          import transformer
          print("✓ Transformer imported successfully")
          EOF

      - name: Cleaner import test
        run: |
          python - <<EOF
          import sys
          sys.path.insert(0, 'cleaner')
          import cleaner
          print("✓ Cleaner imported successfully")
          EOF